name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        check-latest: true
    - uses: dominikh/staticcheck-action@v1
      with:
        install-go: false
        version: "latest"
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test -coverprofile=coverage.txt -v ./...
    - name: Build
      run: go build -v ./...
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
